-- Habilita varios colegios sin separar el proyecto Supabase.
-- La institución existente se conserva y recibe todos los registros actuales.
begin;

create schema if not exists private;

create table if not exists public.colegios (
  id_colegio bigint generated by default as identity primary key,
  nombre text not null,
  slug text not null unique,
  plan text not null default 'Inicial',
  estado text not null default 'PRUEBA'
    check (estado in ('ACTIVO','PRUEBA','SUSPENDIDO','CANCELADO')),
  fecha_registro timestamptz not null default now()
);

insert into public.colegios (nombre, slug, plan, estado)
values ('SAN PIO X- CIRCA', 'san-pio-x-circa', 'Inicial', 'ACTIVO')
on conflict (slug) do update set nombre = excluded.nombre;

alter table public.asistencias add column if not exists id_colegio bigint;
alter table public.configuracion_asistencia add column if not exists id_colegio bigint;
alter table public.configuracion_sistema add column if not exists id_colegio bigint;
alter table public.dias_no_laborables add column if not exists id_colegio bigint;
alter table public.estudiantes add column if not exists id_colegio bigint;
alter table public.grados add column if not exists id_colegio bigint;
alter table public.perfiles add column if not exists id_colegio bigint;
alter table public.registro_actividades add column if not exists id_colegio bigint;
alter table public.secciones add column if not exists id_colegio bigint;

update public.asistencias set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.configuracion_asistencia set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.configuracion_sistema set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.dias_no_laborables set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.estudiantes set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.grados set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.perfiles set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.registro_actividades set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;
update public.secciones set id_colegio = (select id_colegio from public.colegios where slug='san-pio-x-circa') where id_colegio is null;

alter table public.asistencias alter column id_colegio set not null;
alter table public.configuracion_asistencia alter column id_colegio set not null;
alter table public.configuracion_sistema alter column id_colegio set not null;
alter table public.dias_no_laborables alter column id_colegio set not null;
alter table public.estudiantes alter column id_colegio set not null;
alter table public.grados alter column id_colegio set not null;
alter table public.registro_actividades alter column id_colegio set not null;
alter table public.secciones alter column id_colegio set not null;

alter table public.asistencias add constraint asistencias_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete restrict;
alter table public.configuracion_asistencia add constraint configuracion_asistencia_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.configuracion_sistema add constraint configuracion_sistema_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.dias_no_laborables add constraint dias_no_laborables_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.estudiantes add constraint estudiantes_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.grados add constraint grados_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.perfiles add constraint perfiles_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete restrict;
alter table public.registro_actividades add constraint registro_actividades_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;
alter table public.secciones add constraint secciones_id_colegio_fkey foreign key (id_colegio) references public.colegios(id_colegio) on delete cascade;

-- Las claves de negocio pasan a ser únicas dentro de cada colegio.
alter table public.grados drop constraint if exists grados_nombre_key;
alter table public.grados add constraint grados_colegio_nombre_key unique (id_colegio,nombre);
alter table public.estudiantes drop constraint if exists estudiantes_codigo_key;
alter table public.estudiantes add constraint estudiantes_colegio_codigo_key unique (id_colegio,codigo);
alter table public.estudiantes drop constraint if exists estudiantes_dni_key;
alter table public.estudiantes add constraint estudiantes_colegio_dni_key unique (id_colegio,dni);
alter table public.dias_no_laborables drop constraint if exists dias_no_laborables_fecha_key;
alter table public.dias_no_laborables add constraint dias_no_laborables_colegio_fecha_key unique (id_colegio,fecha);

alter table public.grados add constraint grados_colegio_id_key unique (id_colegio,id_grado);
alter table public.secciones add constraint secciones_colegio_id_key unique (id_colegio,id_seccion);
alter table public.estudiantes add constraint estudiantes_colegio_id_key unique (id_colegio,id_estudiante);
alter table public.secciones drop constraint if exists fk_seccion_grado;
alter table public.secciones add constraint fk_seccion_grado_mismo_colegio foreign key (id_colegio,id_grado) references public.grados(id_colegio,id_grado) on update cascade on delete restrict;
alter table public.estudiantes drop constraint if exists fk_estudiante_seccion;
alter table public.estudiantes add constraint fk_estudiante_seccion_mismo_colegio foreign key (id_colegio,id_seccion) references public.secciones(id_colegio,id_seccion) on update cascade on delete restrict;
alter table public.asistencias drop constraint if exists fk_asistencia_estudiante;
alter table public.asistencias add constraint fk_asistencia_estudiante_mismo_colegio foreign key (id_colegio,id_estudiante) references public.estudiantes(id_colegio,id_estudiante) on update cascade on delete restrict;
alter table public.asistencias drop constraint if exists uq_asistencia_estudiante_fecha;
alter table public.asistencias add constraint uq_asistencia_colegio_estudiante_fecha unique (id_colegio,id_estudiante,fecha);
create index if not exists idx_asistencias_colegio_fecha on public.asistencias(id_colegio,fecha desc);
create index if not exists idx_estudiantes_colegio_seccion on public.estudiantes(id_colegio,id_seccion);
create index if not exists idx_perfiles_colegio on public.perfiles(id_colegio);

insert into public.roles (nombre,descripcion,activo)
values ('SUPERADMIN','Administración global de la plataforma',true)
on conflict (nombre) do update set descripcion=excluded.descripcion,activo=true;

alter table public.colegios enable row level security;
revoke all on public.colegios from anon,authenticated;
grant select on public.colegios to authenticated;
grant all on public.colegios to service_role;
revoke all on sequence public.colegios_id_colegio_seq from public,anon,authenticated;
grant usage,select on sequence public.colegios_id_colegio_seq to service_role;

create or replace function private.usuario_puede_acceder_colegio(p_id_colegio bigint, p_roles text[] default array[]::text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.perfiles p join public.roles r on r.id_rol=p.id_rol
    where p.id_usuario=(select auth.uid()) and p.activo and r.activo
      and ((r.nombre='SUPERADMIN' and (cardinality(p_roles)=0 or r.nombre=any(p_roles)))
        or (p.id_colegio=p_id_colegio and (cardinality(p_roles)=0 or r.nombre=any(p_roles))))
  );
$$;
revoke all on function private.usuario_puede_acceder_colegio(bigint,text[]) from public,anon;
grant usage on schema private to authenticated;
grant execute on function private.usuario_puede_acceder_colegio(bigint,text[]) to authenticated;

create or replace function private.asignar_colegio_al_insertar()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_colegio bigint; v_rol text;
begin
  if (select auth.uid()) is not null then
    select p.id_colegio,r.nombre into v_colegio,v_rol
      from public.perfiles p join public.roles r on r.id_rol=p.id_rol
      where p.id_usuario=(select auth.uid()) and p.activo and r.activo;
    if v_rol is distinct from 'SUPERADMIN' then new.id_colegio := v_colegio; end if;
  end if;
  return new;
end;
$$;
revoke all on function private.asignar_colegio_al_insertar() from public,anon,authenticated;

do $$
declare t text;
begin
  foreach t in array array['asistencias','configuracion_asistencia','configuracion_sistema','dias_no_laborables','estudiantes','grados','registro_actividades','secciones'] loop
    execute format('drop trigger if exists asignar_colegio on public.%I',t);
    execute format('create trigger asignar_colegio before insert on public.%I for each row execute function private.asignar_colegio_al_insertar()',t);
  end loop;
end $$;

-- Quita políticas globales anteriores: las políticas permisivas se combinan con OR.
do $$
declare t text; p record;
begin
  foreach t in array array['asistencias','configuracion_asistencia','configuracion_sistema','dias_no_laborables','estudiantes','grados','perfiles','registro_actividades','secciones','colegios','roles'] loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t loop
      execute format('drop policy %I on public.%I',p.policyname,t);
    end loop;
  end loop;
end $$;

create policy colegio_lectura_miembros on public.colegios for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array[]::text[]));
create policy roles_lectura_staff on public.roles for select to authenticated using (true);

create policy perfiles_lectura_propios_y_director on public.perfiles for select to authenticated
  using (id_usuario=(select auth.uid()) or private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy perfiles_insert_director_colegio on public.perfiles for insert to authenticated
  with check (id_colegio is not null and private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy perfiles_actualizar_director_colegio on public.perfiles for update to authenticated
  using (id_usuario<>(select auth.uid()) and private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]))
  with check (id_usuario<>(select auth.uid()) and private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[])
    and exists (select 1 from public.roles r where r.id_rol=perfiles.id_rol and r.nombre<>'SUPERADMIN'));

create policy asistencias_lectura_colegio on public.asistencias for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy asistencias_gestion_colegio on public.asistencias for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));

create policy estudiantes_lectura_colegio on public.estudiantes for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy estudiantes_gestion_colegio on public.estudiantes for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]));

create policy grados_lectura_colegio on public.grados for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy grados_gestion_colegio on public.grados for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]));

create policy secciones_lectura_colegio on public.secciones for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy secciones_gestion_colegio on public.secciones for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR']::text[]));

create policy config_asistencia_lectura_colegio on public.configuracion_asistencia for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy config_asistencia_gestion_director on public.configuracion_asistencia for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy config_sistema_lectura_colegio on public.configuracion_sistema for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy config_sistema_gestion_director on public.configuracion_sistema for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy dias_lectura_colegio on public.dias_no_laborables for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));
create policy dias_gestion_director on public.dias_no_laborables for all to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]))
  with check (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy actividad_lectura_director on public.registro_actividades for select to authenticated
  using (private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR']::text[]));
create policy actividad_insertar_mi_colegio on public.registro_actividades for insert to authenticated
  with check (id_usuario=(select auth.uid()) and private.usuario_puede_acceder_colegio(id_colegio,array['DIRECTOR','ADMINISTRADOR','AUXILIAR']::text[]));

-- Reemplaza las RPC públicas por variantes que siempre reciben un identificador de colegio.
drop function if exists public.buscar_estudiante_asistencia(text);
drop function if exists public.registrar_asistencia_publica(text);
drop function if exists public.obtener_identidad_publica_colegio();

create function public.buscar_estudiante_asistencia(p_codigo text, p_colegio_slug text default 'san-pio-x-circa')
returns table (codigo text,nombres text,apellidos text,grado text,nivel text,seccion text)
language sql stable security definer set search_path = '' as $$
  select e.codigo::text,e.nombres::text,e.apellidos::text,g.nombre::text,g.nivel::text,s.nombre::text
  from public.estudiantes e join public.secciones s on s.id_colegio=e.id_colegio and s.id_seccion=e.id_seccion and s.activo
  join public.grados g on g.id_colegio=s.id_colegio and g.id_grado=s.id_grado and g.activo
  join public.colegios c on c.id_colegio=e.id_colegio and c.estado in ('ACTIVO','PRUEBA')
  where c.slug=p_colegio_slug and e.codigo=btrim(p_codigo) and e.activo limit 1
$$;

create function public.registrar_asistencia_publica(p_codigo text, p_colegio_slug text default 'san-pio-x-circa')
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_config record; v_id_colegio bigint; v_estudiante bigint; v_fecha date; v_hora time; v_dia smallint; v_estado text; v_motivo text; v_saved public.asistencias%rowtype;
begin
  if p_codigo is null or btrim(p_codigo)='' then raise exception 'Código de estudiante no válido' using errcode='22023'; end if;
  select id_colegio into v_id_colegio from public.colegios where slug=p_colegio_slug and estado in ('ACTIVO','PRUEBA');
  if v_id_colegio is null then raise exception 'Colegio no encontrado o inactivo' using errcode='P0002'; end if;
  select hora_inicio,hora_tardanza,hora_falta,dias_laborables into v_config from public.configuracion_asistencia where id_colegio=v_id_colegio and activo order by id_configuracion limit 1;
  if not found then raise exception 'No hay una configuración de asistencia activa' using errcode='P0001'; end if;
  select e.id_estudiante into v_estudiante from public.estudiantes e join public.secciones s on s.id_colegio=e.id_colegio and s.id_seccion=e.id_seccion and s.activo join public.grados g on g.id_colegio=s.id_colegio and g.id_grado=s.id_grado and g.activo where e.id_colegio=v_id_colegio and e.codigo=btrim(p_codigo) and e.activo;
  if not found then raise exception 'Estudiante no encontrado o inactivo' using errcode='P0002'; end if;
  v_fecha := (now() at time zone 'America/Lima')::date; v_hora := (now() at time zone 'America/Lima')::time; v_dia := extract(dow from v_fecha)::smallint;
  select motivo into v_motivo from public.dias_no_laborables where id_colegio=v_id_colegio and fecha=v_fecha and activo;
  if found then return jsonb_build_object('resultado','NO_LABORABLE','motivo',v_motivo,'fecha',v_fecha); end if;
  if not (v_dia=any(v_config.dias_laborables)) then return jsonb_build_object('resultado','NO_LABORABLE','motivo','Hoy no hay clases según el calendario semanal','fecha',v_fecha); end if;
  v_estado := case when v_hora>=v_config.hora_falta then 'FALTA' when v_hora>=v_config.hora_tardanza then 'TARDANZA' else 'PRESENTE' end;
  insert into public.asistencias(id_colegio,id_estudiante,fecha,hora_ingreso,estado) values(v_id_colegio,v_estudiante,v_fecha,v_hora,v_estado) on conflict(id_colegio,id_estudiante,fecha) do nothing returning * into v_saved;
  if found then return jsonb_build_object('resultado','REGISTRADO','estado',v_saved.estado,'fecha',v_saved.fecha,'hora_ingreso',v_saved.hora_ingreso); end if;
  select estado,fecha,hora_ingreso into v_saved.estado,v_saved.fecha,v_saved.hora_ingreso from public.asistencias where id_colegio=v_id_colegio and id_estudiante=v_estudiante and fecha=v_fecha;
  return jsonb_build_object('resultado','DUPLICADO','estado',v_saved.estado,'fecha',v_saved.fecha,'hora_ingreso',v_saved.hora_ingreso);
end;
$$;

create function public.obtener_identidad_publica_colegio(p_colegio_slug text default 'san-pio-x-circa')
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('nombre_colegio',s.nombre_colegio,'lema',s.lema,'logo_url',s.logo_url,'color_principal',s.color_principal,'color_secundario',s.color_secundario,'color_fondo',s.color_fondo,'modo',s.modo)
  from public.configuracion_sistema s join public.colegios c on c.id_colegio=s.id_colegio
  where c.slug=p_colegio_slug and c.estado in ('ACTIVO','PRUEBA') order by s.id_configuracion limit 1
$$;

revoke all on function public.buscar_estudiante_asistencia(text,text) from public,authenticated;
revoke all on function public.registrar_asistencia_publica(text,text) from public,authenticated;
revoke all on function public.obtener_identidad_publica_colegio(text) from public,authenticated;
grant execute on function public.buscar_estudiante_asistencia(text,text) to anon;
grant execute on function public.registrar_asistencia_publica(text,text) to anon;
grant execute on function public.obtener_identidad_publica_colegio(text) to anon;

commit;
